# Generated by Django 5.1.15 on 2026-09-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('experience', models.CharField(blank=True, help_text="e.g. '3-5 years'.", max_length=100)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated.', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'careers_jobposting',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'department'], name='careers_job_is_acti_104220_idx')],
            },
        ),
    ]
