# Generated by Django 5.1.15 on 2026-09-06 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='Drives /services/<slug>.', max_length=150, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('long_description', models.TextField(blank=True, help_text='Sanitized HTML (docs/SECURITY.md).')),
                ('business_value', models.TextField(blank=True)),
                ('standards_codes', models.TextField(blank=True, help_text='Applicable industry standards/codes.')),
                ('deliverables', models.TextField(blank=True)),
                ('output_formats', models.CharField(blank=True, help_text="e.g. 'DWG, PDF, REVIT'.", max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_icon_set+', to='media.mediaasset')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_og_set+', to='media.mediaasset')),
                ('technology', models.ManyToManyField(blank=True, related_name='services', to='technology.technology')),
            ],
            options={
                'db_table': 'services_service',
                'ordering': ['display_order', 'name'],
                'permissions': [('publish_service', 'Can publish service')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='services.service')),
            ],
            options={
                'db_table': 'services_servicecapability',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
                'db_table': 'services_servicefaq',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('step_number', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='services.service')),
            ],
            options={
                'db_table': 'services_serviceprocessstep',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'display_order'], name='services_se_status_12918d_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceprocessstep',
            constraint=models.UniqueConstraint(fields=('service', 'step_number'), name='uniq_process_step_per_service'),
        ),
    ]
