# Generated by Django 5.1.15 on 2026-09-06 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['page_key', 'display_order'], 'permissions': [('publish_pagesection', 'Can publish/unpublish/archive page sections')]},
        ),
        migrations.AddField(
            model_name='pagesection',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.contentversion'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Set when status last became PUBLISHED.', null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='If set on an APPROVED section, a Celery beat task publishes it at this time.', null=True),
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['status', 'scheduled_publish_at'], name='pages_pages_status_3e388f_idx'),
        ),
    ]
