# Generated by Django 5.1.15 on 2026-09-06 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagesection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_path', models.CharField(db_index=True, help_text="Path only, leading slash, no host: '/services/old-slug'.", max_length=400, unique=True)),
                ('new_path', models.CharField(help_text="Where 'old_path' should now go.", max_length=400)),
                ('is_permanent', models.BooleanField(default=True, help_text='301 when true, 302 when false.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pages_redirect',
                'ordering': ['old_path'],
            },
        ),
    ]
