"""
Quote requests (spec §17). Public reference numbers (MDS-Q-2026-000001)
are generated by `services.generate_quote_reference` using a per-year
counter row locked with SELECT FOR UPDATE inside a transaction — never
`count() + 1`, which races under concurrent submissions.
"""
from django.conf import settings
from django.db import models

from apps.documents.models import Document
from apps.markets.models import Country
from apps.services.models import Service


class QuoteStatus(models.TextChoices):
    NEW = "new", "New"
    ASSIGNED = "assigned", "Assigned"
    IN_PROGRESS = "in_progress", "In Progress"
    RESPONDED = "responded", "Responded"
    CLOSED = "closed", "Closed"
    SPAM = "spam", "Spam"


class QuoteReferenceSequence(models.Model):
    """One row per year; the counter `generate_quote_reference` locks and
    increments. Not exposed via any API — internal to reference
    generation only."""

    year = models.PositiveIntegerField(unique=True)
    last_number = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = "quotations_referencesequence"


class QuoteRequest(models.Model):
    public_reference = models.CharField(max_length=30, unique=True, editable=False, db_index=True)

    name = models.CharField(max_length=150)
    company = models.CharField(max_length=150, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=30, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.SET_NULL, related_name="+")

    service = models.ForeignKey(
        Service, null=True, blank=True, on_delete=models.SET_NULL, related_name="quote_requests"
    )
    required_services = models.ManyToManyField(Service, blank=True, related_name="+")
    project_type = models.CharField(max_length=150, blank=True)
    project_location = models.CharField(max_length=255, blank=True)
    project_size = models.CharField(max_length=100, blank=True)
    timeline = models.CharField(max_length=100, blank=True)
    message = models.TextField(blank=True)

    status = models.CharField(max_length=20, choices=QuoteStatus.choices, default=QuoteStatus.NEW)
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, related_name="+"
    )

    idempotency_key = models.CharField(max_length=255, unique=True, null=True, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=500, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "quotations_quoterequest"
        ordering = ["-created_at"]
        permissions = [
            ("assign_quoterequest", "Can assign quote request"),
            ("close_quoterequest", "Can close quote request"),
        ]
        indexes = [models.Index(fields=["status", "-created_at"])]

    def __str__(self) -> str:
        return self.public_reference


class QuoteAttachment(models.Model):
    quote = models.ForeignKey(QuoteRequest, on_delete=models.CASCADE, related_name="attachments")
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name="+")

    class Meta:
        db_table = "quotations_quoteattachment"
