# Generated by Django 5.1.15 on 2026-09-06 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('nda', 'NDA / Confidentiality'), ('data_security', 'Data Security & Compliance')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, help_text='Sanitized HTML (docs/SECURITY.md).')),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_legaldocument',
                'ordering': ['document_type'],
                'permissions': [('publish_legaldocument', 'Can publish legal document')],
            },
        ),
    ]
