# Generated by Django 5.1.15 on 2026-09-06 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('brochure', 'Brochure'), ('video', 'Video'), ('sample_drawing', 'Sample Drawing'), ('technical_document', 'Technical Document'), ('case_study', 'Case Study'), ('whitepaper', 'Whitepaper')], max_length=30)),
                ('external_url', models.URLField(blank=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted')], default='public', max_length=10)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'db_table': 'resources_resource',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['is_published', 'category'], name='resources_r_is_publ_657fe7_idx')],
            },
        ),
    ]
